version: "3.8"

services:
  telegram:
    build: .
    container_name: telegram
    hostname: telegram
    network_mode: "host"
    env_file:
      - ./.env
    ports:
      - "7040:7040"
    volumes:
      - ./src:/src/

  mongodb:
    image: mongo:latest
    container_name: mongodb
    hostname: mongodb
    env_file:
      - ./.env
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db

volumes:
  mongodb: