version: "3.5"

volumes:
  mongodb:

services:

  mongodb:
    image: mongo:latest
    container_name: mongodb
    networks:
      - infnet
    env_file:
      - ./.env
    volumes:
      - mongodb:/data/db

networks:
  infnet:
    name: infr_network
