version: "3.3"

services:
  telegram:
    build: .
    container_name: telegram
    restart: always
    hostname: telegram
    networks:
      - maininfrnet
    env_file:
      - ./.env
    ports:
      - 7040:7040
    entrypoint: ["gunicorn src.core.application:application --bind 0.0.0.0:7040 --worker-class aiohttp.Gunico      rnWebWorker"]

networks:
  maininfrnet:
    external:
      name: infr_network  
